name: 'Copr test'
description: 'TiDB Copr Test'
inputs:
  tidb-commit-id:
    description: 'tidb-commit-id'
    required: true
    default: '7647c2b9b0b08b4995a8b58e47000cf7cd0b3240'
  tikv-commit-id:
    description: 'tikv-commit-id'
    required: true
    default: 'ef3f7917ed9bf1755e89a0abdc7804d9c5de8fda'
  pd-commit-id:
    description: 'pd-commit-id'
    required: true
    default: '909f2fdebb3f06b704dfc4498b498708efe9ee32'
outputs:
  copr-result:
    description: "Result of copr"
    value: ${{ steps.copr-test.outputs }}
runs:
  using: "composite"
  steps:
    - name: Pull binaries down && extract
      shell: bash
      run: |
        wget -q http://fileserver.pingcap.net/download/builds/pingcap/tikv/${{ inputs.tikv-commit-id }}/centos7/tikv-server.tar.gz
        wget -q http://fileserver.pingcap.net/download/builds/pingcap/tidb/${{ inputs.tidb-commit-id }}/centos7/tidb-server.tar.gz
        wget -q http://fileserver.pingcap.net/download/builds/pingcap/pd/${{ inputs.pd-commit-id }}/centos7/pd-server.tar.gz

        mkdir pd tidb tikv
        tar -xf pd-server.tar.gz -C pd
        tar -xf tikv-server.tar.gz -C tikv
        tar -xf tidb-server.tar.gz -C tidb

    - name: copr-test
      id: copr-test
      shell: bash
      run: |
        ls && pwd
        pd_bin=$(pwd)/pd/bin/pd-server tikv_bin=$(pwd)/tikv/bin/tikv-server tidb_src_dir=$(pwd)/tidb make push-down-test

